### ISSUE TITLE
feat: Implement tool for downloading from Yandex.Disk

### ISSUE THREAD

**Issue by RKulagin** [RKulagin/PKMS#3]

**Comment by RKulagin** [comment]
Необходимо выводить имя папок в текущем каталоге, предлагать скачивать либо целую папку, либо перейти в неё и скачать какой-то конкретный файл внутри.

**Comment by L1p7on** [comment]
1.  Вывести папки корня.
2. До ключевого слова выводить папки и переходить в одну из них. (переходить по номеру)
3. по респонсу создавать бинарный файл с тем же именем.

**Comment by L1p7on** [comment]
getd to download directory
